application: chrisamywedding-vote
version: 1
runtime: python
api_version: 1

inbound_services:
- channel_presence

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: main.py
